# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: user_base_development
  host: localhost
  user: root
  password: password
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  database: user_base_test
  user: root
  password: password
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: user_base_development
  host: localhost
  user: root
  password: password
  pool: 5
  timeout: 5000

